# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 2 Bit Hacker
email: chip@2bithacker.net
description: > # this means to ignore newlines until "baseurl:"
   Random stuff from a network engineer / developer and FreeBSD enthusiast.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://2bithacker.github.io" # the base hostname & protocol for your site
twitter_username: 2bithacker
github_username:  2bithacker

# Build settings
markdown: kramdown
